# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 02:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Serial', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='size',
            new_name='type_size',
        ),
    ]
