# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='photo',
            field=models.ImageField(default='uploads/no-img.png', upload_to='uploads'),
        ),
    ]
