# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serial', '0002_auto_20171114_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
