# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serial', '0002_auto_20171116_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='type_size',
            field=models.CharField(max_length=60),
        ),
    ]
