# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serial', '0002_auto_20180109_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_directory_path'),
        ),
    ]
