# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Serial', '0003_device_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='maker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='devices_created', to='Serial.Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spec',
            name='device_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='Serial.Device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spec',
            name='maker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='makers', to='Serial.Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='type',
            name='maker',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
