# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serial', '0004_auto_20180109_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='maker',
            name='maker_url',
            field=models.URLField(default='http://www.<django.db.models.fields.CharField>.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='photo',
            field=models.ImageField(blank=True, default='img/no-img.jpg', null=True, upload_to='img/%Y-%m-%d'),
        ),
    ]
