# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 04:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Serial', '0004_auto_20171114_0403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='maker',
        ),
        migrations.AddField(
            model_name='device',
            name='maker',
            field=models.ManyToManyField(to='Serial.Type'),
        ),
        migrations.RemoveField(
            model_name='device',
            name='type',
        ),
        migrations.AddField(
            model_name='device',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='devices_created', to='Serial.Type'),
            preserve_default=False,
        ),
    ]
