# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 04:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Serial', '0005_auto_20171114_0408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spec',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='spec',
            name='maker',
        ),
        migrations.RemoveField(
            model_name='device',
            name='maker',
        ),
        migrations.DeleteModel(
            name='Spec',
        ),
    ]
