# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Serial', '0005_auto_20180123_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maker',
            name='maker_url',
        ),
    ]
