# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Serial', '0006_auto_20171114_0414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.RenameField(
            model_name='type',
            old_name='maker',
            new_name='size',
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_type', to='Serial.Type'),
        ),
        migrations.AddField(
            model_name='device',
            name='maker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='device_creator', to='Serial.Maker'),
            preserve_default=False,
        ),
    ]
