# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serial', '0006_remove_maker_maker_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='maker',
            name='maker_type',
            field=models.CharField(default='Manufacturer', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='photo',
            field=models.ImageField(blank=True, default='img/no-img.jpeg', null=True, upload_to='img/%Y-%m-%d'),
        ),
    ]
