# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Serial', '0007_auto_20171114_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='type',
            new_name='type_name',
        ),
    ]
