# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Serial', '0008_auto_20171114_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='photo',
        ),
    ]
