# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serial', '0009_remove_device_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
